### ISSUE TITLE
error: `son/download.py`

### ISSUE THREAD

**Issue by keicoon** [keicoon/multi-speaker-tacotron-tensorflow#6]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/datasets/son/download.py", line 41, in download_news_video_and_content
    makedirs(video_dir)
  File "/home/utils/__init__.py", line 66, in makedirs
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/datasets/son/video'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/datasets/son/download.py", line 150, in <module>
    fn, news_ids, desc="Download news video+text", parallel=True)
  File "/home/utils/__init__.py", line 146, in parallel_run
    fn, items), total=len(items), desc=desc):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 949, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
FileExistsError: [Errno 17] File exists: '/home/datasets/son/video'
```

**Comment by keicoon** [comment]
solve : a18e4ea522388e0d963916026de5d796744979d1
